# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170425_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shelf_location',
            field=models.CharField(choices=[('Business & I.T', 'Business & I.T'), ('Economics', 'Economics'), ('I.T', 'I.T'), ('Law', 'Law'), ('Mathematics', 'Mathematics'), ('Medicine', 'Medicine'), ('Scialogy', 'Socialogy')], default='choose location', max_length=100, verbose_name='shelf_location'),
        ),
    ]
