# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170423_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, help_text='dd/mm/yy', null=True),
        ),
    ]
